### PR TITLE
add C Callable earcut

### PR DESCRIPTION
**Pull request by mdsumner**
My first C Callable function, thanks to @dcooley as [discussed here](https://github.com/hypertidy/geodist/issues/24)

The tests include an example: 

```R
  library(Rcpp)
  cppFunction(
    code = '
    SEXP earcut( SEXP x , SEXP y, SEXP holes, SEXP numholes) {
      typedef SEXP R_DECIDO_FUN(SEXP, SEXP, SEXP, SEXP);
      R_DECIDO_FUN *decido_earcut_cpp = (R_DECIDO_FUN *) R_GetCCallable("decido","decido_earcut_cpp");
      return decido_earcut_cpp( x, y, holes, numholes );
    }
  '
  )


  ## single ring polygon
  x <- c(0, 0, 0.75, 1, 0.5, 0.8, 0.69)
  y <- c(0, 1, 1, 0.8, 0.7, 0.6, 0)
  (ind <- earcut(x, y, 0L, 0L))
  expect_equal(ind, c(1L, 0L, 6L, 6L, 5L, 4L, 4L, 3L, 2L, 1L, 6L, 4L, 4L, 2L, 1L))
 # plot_ears(cbind(x, y), ind + 1)  ## plus 1 because C++ context (the R-level translates)

```

### CODE REVIEW

**Comment by dcooley** [comment]
Nice one Michael.

Another approach you could consider is, since earcut is a header-only library itself, you could move `earcut.h` into `/inst/include/`, then other packages will be able to `LinkingTo: decido` in the DESCRIPTION and it should work as well.

**Comment by mdsumner** [comment]
Oh yes, right I see

**Comment by dcooley** [comment]
Will need an additional line in [Makevars](https://github.com/dcooley/sfheaders/blob/master/src/Makevars#L3) too if you do it that way

```
CXX_STD = CXX11

PKG_CXXFLAGS = -I../inst/include/
```

**Comment by dcooley** [comment]
I now have a [use-case](https://github.com/SymbolixAU/mapdeck/issues/298) for this. If you don't have any strong opinions either way, I'd prefer to have the `/Inst/include/` linkable header, rather than the Callable routine.

**Comment by mdsumner** [comment]
I don't have a strong opinion here, I also don't have capacity to look at it rn but will merge a PR if you do

**Comment by dcooley** [comment]
ok cool. I'm not in a rush yet; I first need to work out how to build the underlying Deckgl layer. But I'll work on a PR nonetheless.

**Pull request closed without merging**
