### PR TITLE
add decido.h

### PR DESCRIPTION
**Pull request by mpadge**
This suppresses the only -Wall notes of 'no previous prototype' for #21

### CODE REVIEW

**Comment by mdsumner** [comment]
Nice, thanks!

**Comment by mpadge** [comment]
@mdsumner This is my generic code that i use for these checks:
``` r
cpp_flgs <- c_flgs <- "-Wall -pedantic -Werror -Wconversion -Wsign-compare -Weverything -Wno-c++98-compat"
setwd (here::here ("src"))
# The -isystem commands suppress warnings from those linked files
cmd_base <- paste ("-I/usr/include/R -DNDEBUG",
                   "-I../inst/include",
                  "-I\"/usr/lib/R/library/Rcpp/include\"",
                  "-I\"/usr/lib/R/library/RcppParallel/include\"",
                  "-fpic",
                  "-isystem ../inst/include",
                  "-isystem /usr/lib/R/library/Rcpp/include",
                  "-isystem /usr/lib/R/library/RcppParallel/include",
                  "-g -O2 -fstack-protector-strong -Wformat",
                  "-Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g")

flist_cpp <- list.files (".", pattern = "\\.cpp")
f <- flist_cpp [!grepl ("RcppExports", flist_cpp)]

for (f in flist) {
    obj <- paste0 (tools::file_path_sans_ext (f), ".o")
    cmd <- paste ("clang++ -std=gnu++11 -fsanitize=undefined -ferror-limit=100",
                  cmd_base, cpp_flgs, "-c", f, "-o", obj)
    message (cmd)
    system (cmd)
}
```
You'll need to adjust the paths to your system (from paths in `installed.packages()`, as well as path to `/usr/include/R`, but all should be easy. You might not want all flags (like `-g`), but tweak as you like. I should put this in some kinda package one day, i guess ...? It's also not too hard to then modify that to do your own local `ASAN`/`UBSAN` checks (hence the `-g`, because that's needed to get useful output from those).

**Comment by mdsumner** [comment]
Wow, thanks - this is way more than I expected!

**Comment by mpadge** [comment]
But once you start doing that, you'll never look back. I couldn't live without those lines

**Comment by mdsumner** [comment]
Brilliant, I've applied this to the area package and now things are sweet (maybe other random luck helped too ...)

https://github.com/hypertidy/area#area

**Pull request merged**
